export const serviceList = [
    { Title: 'Drake',     img: '/img/Services/service-1.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-2.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-3.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-4.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-5.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-6.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-7.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-8.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-9.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-10.jpg' },   
    { Title: 'Drake',     img: '/img/Services/service-11.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-12.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-13.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-14.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-15.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-16.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-17.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-18.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-19.jpg' },
    { Title: 'Drake',     img: '/img/Services/service-20.jpg' },
];  